// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.2
// source: proto/protocol.proto

package netdog

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileHeader struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filename     string `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Filesize     int64  `protobuf:"varint,2,opt,name=filesize,proto3" json:"filesize,omitempty"`
	Checksum     string `protobuf:"bytes,3,opt,name=checksum,proto3" json:"checksum,omitempty"`
	ChecksumAlgo string `protobuf:"bytes,4,opt,name=checksum_algo,json=checksumAlgo,proto3" json:"checksum_algo,omitempty"`
}

func (x *FileHeader) Reset() {
	*x = FileHeader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_protocol_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileHeader) ProtoMessage() {}

func (x *FileHeader) ProtoReflect() protoreflect.Message {
	mi := &file_proto_protocol_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileHeader.ProtoReflect.Descriptor instead.
func (*FileHeader) Descriptor() ([]byte, []int) {
	return file_proto_protocol_proto_rawDescGZIP(), []int{0}
}

func (x *FileHeader) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *FileHeader) GetFilesize() int64 {
	if x != nil {
		return x.Filesize
	}
	return 0
}

func (x *FileHeader) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *FileHeader) GetChecksumAlgo() string {
	if x != nil {
		return x.ChecksumAlgo
	}
	return ""
}

type GroupFileHeader struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type  string        `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Files []*FileHeader `protobuf:"bytes,2,rep,name=files,proto3" json:"files,omitempty"`
}

func (x *GroupFileHeader) Reset() {
	*x = GroupFileHeader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_protocol_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GroupFileHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupFileHeader) ProtoMessage() {}

func (x *GroupFileHeader) ProtoReflect() protoreflect.Message {
	mi := &file_proto_protocol_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupFileHeader.ProtoReflect.Descriptor instead.
func (*GroupFileHeader) Descriptor() ([]byte, []int) {
	return file_proto_protocol_proto_rawDescGZIP(), []int{1}
}

func (x *GroupFileHeader) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GroupFileHeader) GetFiles() []*FileHeader {
	if x != nil {
		return x.Files
	}
	return nil
}

var File_proto_protocol_proto protoreflect.FileDescriptor

var file_proto_protocol_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x6e, 0x65, 0x74, 0x64, 0x6f, 0x67, 0x22, 0x85,
	0x01, 0x0a, 0x0a, 0x46, 0x69, 0x6c, 0x65, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x1a, 0x0a,
	0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c,
	0x65, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x66, 0x69, 0x6c,
	0x65, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x73, 0x75,
	0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x73, 0x75,
	0x6d, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x73, 0x75, 0x6d, 0x5f, 0x61, 0x6c,
	0x67, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x73,
	0x75, 0x6d, 0x41, 0x6c, 0x67, 0x6f, 0x22, 0x4f, 0x0a, 0x0f, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x46,
	0x69, 0x6c, 0x65, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x28, 0x0a,
	0x05, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6e,
	0x65, 0x74, 0x64, 0x6f, 0x67, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x52, 0x05, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x6e, 0x65, 0x74,
	0x64, 0x6f, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_protocol_proto_rawDescOnce sync.Once
	file_proto_protocol_proto_rawDescData = file_proto_protocol_proto_rawDesc
)

func file_proto_protocol_proto_rawDescGZIP() []byte {
	file_proto_protocol_proto_rawDescOnce.Do(func() {
		file_proto_protocol_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_protocol_proto_rawDescData)
	})
	return file_proto_protocol_proto_rawDescData
}

var file_proto_protocol_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_protocol_proto_goTypes = []interface{}{
	(*FileHeader)(nil),      // 0: netdog.FileHeader
	(*GroupFileHeader)(nil), // 1: netdog.GroupFileHeader
}
var file_proto_protocol_proto_depIdxs = []int32{
	0, // 0: netdog.GroupFileHeader.files:type_name -> netdog.FileHeader
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_protocol_proto_init() }
func file_proto_protocol_proto_init() {
	if File_proto_protocol_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_protocol_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileHeader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_protocol_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GroupFileHeader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_protocol_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_protocol_proto_goTypes,
		DependencyIndexes: file_proto_protocol_proto_depIdxs,
		MessageInfos:      file_proto_protocol_proto_msgTypes,
	}.Build()
	File_proto_protocol_proto = out.File
	file_proto_protocol_proto_rawDesc = nil
	file_proto_protocol_proto_goTypes = nil
	file_proto_protocol_proto_depIdxs = nil
}
